<?php

namespace ManiaLivePlugins\eXpansion\Helpers;

class Countries
{

    public static $countries = array(
        'Afghanistan' => 'AFG',
        'Albania' => 'ALB',
        'Algeria' => 'ALG',
        'Andorra' => 'AND',
        'Angola' => 'ANG',
        'Argentina' => 'ARG',
        'Armenia' => 'ARM',
        'Aruba' => 'ARU',
        'Australia' => 'AUS',
        'Austria' => 'AUT',
        'Azerbaijan' => 'AZE',
        'Bahamas' => 'BAH',
        'Bahrain' => 'BRN',
        'Bangladesh' => 'BAN',
        'Barbados' => 'BAR',
        'Belarus' => 'BLR',
        'Belgium' => 'BEL',
        'Belize' => 'BIZ',
        'Benin' => 'BEN',
        'Bermuda' => 'BER',
        'Bhutan' => 'BHU',
        'Bolivia' => 'BOL',
        'Bosnia&Herzegovina' => 'BIH',
        'Botswana' => 'BOT',
        'Brazil' => 'BRA',
        'Brunei' => 'BRU',
        'Bulgaria' => 'BUL',
        'Burkina Faso' => 'BUR',
        'Burundi' => 'BDI',
        'Cambodia' => 'CAM',
        'Cameroon' => 'CAR',
        'Canada' => 'CAN',
        'Cape Verde' => 'CPV',
        'Central African Republic' => 'CAF',
        'Chad' => 'CHA',
        'Chile' => 'CHI',
        'China' => 'CHN',
        'Chinese Taipei' => 'TPE',
        'Colombia' => 'COL',
        'Congo' => 'CGO',
        'Costa Rica' => 'CRC',
        'Croatia' => 'CRO',
        'Cuba' => 'CUB',
        'Cyprus' => 'CYP',
        'Czech Republic' => 'CZE',
        'Czech republic' => 'CZE',
        'DR Congo' => 'COD',
        'Denmark' => 'DEN',
        'Djibouti' => 'DJI',
        'Dominica' => 'DMA',
        'Dominican Republic' => 'DOM',
        'Ecuador' => 'ECU',
        'Egypt' => 'EGY',
        'El Salvador' => 'ESA',
        'Eritrea' => 'ERI',
        'Estonia' => 'EST',
        'Ethiopia' => 'ETH',
        'Fiji' => 'FIJ',
        'Finland' => 'FIN',
        'France' => 'FRA',
        'Gabon' => 'GAB',
        'Gambia' => 'GAM',
        'Georgia' => 'GEO',
        'Germany' => 'DEU',
        'Ghana' => 'GHA',
        'Greece' => 'GRE',
        'Grenada' => 'GRN',
        'Guam' => 'GUM',
        'Guatemala' => 'GUA',
        'Guinea' => 'GUI',
        'Guinea-Bissau' => 'GBS',
        'Guyana' => 'GUY',
        'Haiti' => 'HAI',
        'Honduras' => 'HON',
        'Hong Kong' => 'HKG',
        'Hungary' => 'HUN',
        'Iceland' => 'ISL',
        'India' => 'IND',
        'Indonesia' => 'INA',
        'Iran' => 'IRI',
        'Iraq' => 'IRQ',
        'Ireland' => 'IRL',
        'Israel' => 'ISR',
        'Italy' => 'ITA',
        'Ivory Coast' => 'CIV',
        'Jamaica' => 'JAM',
        'Japan' => 'JPN',
        'Jordan' => 'JOR',
        'Kazakhstan' => 'KAZ',
        'Kenya' => 'KEN',
        'Kiribati' => 'KIR',
        'Korea' => 'KOR',
        'Kuwait' => 'KUW',
        'Kyrgyzstan' => 'KGZ',
        'Laos' => 'LAO',
        'Latvia' => 'LAT',
        'Lebanon' => 'LIB',
        'Lesotho' => 'LES',
        'Liberia' => 'LBR',
        'Libya' => 'LBA',
        'Liechtenstein' => 'LIE',
        'Lithuania' => 'LTU',
        'Luxembourg' => 'LUX',
        'Macedonia' => 'MKD',
        'Malawi' => 'MAW',
        'Malaysia' => 'MAS',
        'Mali' => 'MLI',
        'Malta' => 'MLT',
        'Mauritania' => 'MTN',
        'Mauritius' => 'MRI',
        'Mexico' => 'MEX',
        'Moldova' => 'MDA',
        'Monaco' => 'MON',
        'Mongolia' => 'MGL',
        'Montenegro' => 'MNE',
        'Morocco' => 'MAR',
        'Mozambique' => 'MOZ',
        'Myanmar' => 'MYA',
        'Namibia' => 'NAM',
        'Nauru' => 'NRU',
        'Nepal' => 'NEP',
        'Netherlands' => 'NED',
        'New Zealand' => 'NZL',
        'Nicaragua' => 'NCA',
        'Niger' => 'NIG',
        'Nigeria' => 'NGR',
        'Norway' => 'NOR',
        'Oman' => 'OMA',
        'Other Countries' => 'OTH',
        'Pakistan' => 'PAK',
        'Palau' => 'PLW',
        'Palestine' => 'PLE',
        'Panama' => 'PAN',
        'Paraguay' => 'PAR',
        'Peru' => 'PER',
        'Philippines' => 'PHI',
        'Poland' => 'POL',
        'Portugal' => 'POR',
        'Puerto Rico' => 'PUR',
        'Qatar' => 'QAT',
        'Romania' => 'ROM',
        'Russia' => 'RUS',
        'Rwanda' => 'RWA',
        'Samoa' => 'SAM',
        'San Marino' => 'SMR',
        'Saudi Arabia' => 'KSA',
        'Senegal' => 'SEN',
        'Serbia' => 'SCG',
        'Sierra Leone' => 'SLE',
        'Singapore' => 'SIN',
        'Slovakia' => 'SVK',
        'Slovenia' => 'SLO',
        'Somalia' => 'SOM',
        'South Africa' => 'RSA',
        'Spain' => 'ESP',
        'Sri Lanka' => 'SRI',
        'Sudan' => 'SUD',
        'Suriname' => 'SUR',
        'Swaziland' => 'SWZ',
        'Sweden' => 'SWE',
        'Switzerland' => 'SUI',
        'Syria' => 'SYR',
        'Taiwan' => 'TWN',
        'Tajikistan' => 'TJK',
        'Tanzania' => 'TAN',
        'Thailand' => 'THA',
        'Togo' => 'TOG',
        'Tonga' => 'TGA',
        'Trinidad and Tobago' => 'TRI',
        'Tunisia' => 'TUN',
        'Turkey' => 'TUR',
        'Turkmenistan' => 'TKM',
        'Tuvalu' => 'TUV',
        'Uganda' => 'UGA',
        'Ukraine' => 'UKR',
        'United Arab Emirates' => 'UAE',
        'United Kingdom' => 'GBR',
        'United States of America' => 'USA',
        'Uruguay' => 'URU',
        'Uzbekistan' => 'UZB',
        'Vanuatu' => 'VAN',
        'Venezuela' => 'VEN',
        'Vietnam' => 'VIE',
        'Yemen' => 'YEM',
        'Zambia' => 'ZAM',
        'Zimbabwe' => 'ZIM',
    );

    public static function mapCountry($country)
    {
        $countries = self::$countries;

        if (array_key_exists($country, $countries)) {
            $output = $countries[$country];
        } else {
            $output = 'OTH';
        }

        return $output;
    }

    public static function getCountryFromCode($code)
    {
        $countries = self::$countries;
        $code = strtoupper($code);
        if (in_array($code, $countries)) {
            foreach ($countries as $country => $short) {
                if (strtoupper($code) == $short) {
                    $output = $country;
                    break;
                }
            }
        } else {
            $output = 'Other';
        }

        return $output;
    }
}
