<?php

namespace ManiaLivePlugins\eXpansion\Help\Gui\Windows;


use ManiaLive\Gui\Controls\Frame;
use ManiaLivePlugins\eXpansion\Gui\Elements\ScrollableArea;
use ManiaLivePlugins\eXpansion\Gui\Elements\Xml;
use ManiaLivePlugins\eXpansion\Gui\Windows\Window;

class HelpWindow extends Window
{

    protected $scroll;


    public function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $this->scroll = new ScrollableArea(227, 90);
        $this->scroll->setPosition(-1, -4);
        $this->addComponent($this->scroll);

        $markdown = new \Ciconia\Ciconia(new \ManiaLivePlugins\eXpansion\Helpers\Markdown\ManialinkRenderer());
        $markdown->addExtension(new \ManiaLivePlugins\eXpansion\Helpers\Markdown\LineExtension());
        $markdown->removeExtension("paragraph");
        $markdown->removeExtension("code");
        $xml = new Xml();

        $file = file_get_contents(__DIR__ . "/adminguide.md");
        $file = str_replace("<br>", "\n", $file);
        $document = "<frame>" . $markdown->render($file) . "</frame>";


        $sizeY = (substr_count($document, "label auto") * 6) + (substr_count($document, "label style") * 8);

        $xml->setContent($document);

        $frame = new Frame();
        $frame->addComponent($xml);
        $frame->setSize(320, $sizeY);

        $this->scroll->setContent($frame);


    }

}
