<?php

namespace ManiaLivePlugins\eXpansion\Help\Gui\Windows;

use ManiaLib\Gui\Elements\Label;
use ManiaLib\Gui\Elements\Quad;
use ManiaLive\Gui\Controls\Frame;
use ManiaLivePlugins\eXpansion\Gui\Elements\ScrollableArea;
use ManiaLivePlugins\eXpansion\Gui\Windows\Window;

class HelpWindow extends Window
{

    protected $scroll;


    public function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $this->scroll = new ScrollableArea(70, 60);
        $this->scroll->setPositionY(-5);
        $frame = new Frame();
        $quad = new Quad(190,1200);
        $quad->setBgcolor("fff6");
        $frame->addComponent($quad);
        for ($x = 0; $x < 300; $x++) {
            $label = new Label(30, 6);
            $label->setPositionX(rand(0,130));
            $label->setPositionY(-$x * 6);
            $label->setText($x . " Lorem ipsum sum dolomet");
            $frame->addComponent($label);
        }
        $frame->setSize(200, 300*6);

        $this->scroll->setContent($frame);

        $this->addComponent($this->scroll);
    }

}
